default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: 'password'

development:
  <<: *default
  database: freshly_development

test: &test
  <<: *default
  database: freshly_test

production:
